# Generated by Django 2.2.5 on 2019-09-09 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailboxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='customer',
        ),
        migrations.AddField(
            model_name='mailbox',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalagreement',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rental_agreements', to='mailboxes.MailBox'),
        ),
    ]
