# Generated by Django 2.2.5 on 2019-09-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0002_auto_20190909_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
