# Generated by Django 2.2.5 on 2019-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0003_mail_collected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalagreement',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
