# Generated by Django 2.2.5 on 2019-09-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0005_auto_20190911_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='customer',
        ),
    ]
