# Generated by Django 2.2.5 on 2019-09-12 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0007_mailbox_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailboxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
