# Generated by Django 2.2.5 on 2019-09-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailboxes', '0008_auto_20190912_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='customer',
        ),
    ]
